"""
build_secrets_b64.py
====================

Emits a Streamlit secrets block whose service-account key is base64-encoded into
a WRAPPING-PROOF TOML string, then verifies it by parsing it back.

WHY THE FOLDING MATTERS
-----------------------
The PEM private key must be one TOML line, and the base64 blob is ~3,100
characters. Observed on this deployment: the paste path inserts HARD line breaks
into long values, so both forms failed with "Invalid format: please enter valid
TOML" -- a raw newline is illegal inside a TOML basic string.

The fix is TOML's own line-folding: a triple-quoted string where each line ends
with a backslash. The parser strips the trailing newline and joins the pieces, so
a hard break becomes harmless:

    gcp_service_account_b64 = \"\"\"
    AAAA...\\
    BBBB...\\
    CCCC\"\"\"

parses to "AAAABBBBCCCC" regardless of where the lines break.

    python build_secrets_b64.py                 # writes .streamlit/secrets.toml
    python build_secrets_b64.py --spreadsheet-id X --credentials Y --out Z
"""

from __future__ import annotations

import argparse
import base64
import json
import pathlib
import sys
import textwrap

DEFAULT_SPREADSHEET_ID = "1BIizam6JvfXW1YX6sxJS5pB4aKBj77Vdn09uvKmjMcg"
FOLD_WIDTH = 76


def build_block(spreadsheet_id: str, encoded: str) -> str:
    """Return the complete secrets.toml text."""
    body = textwrap.wrap(encoded, FOLD_WIDTH)
    if not body:
        raise ValueError("empty base64 payload")

    lines: list[str] = [
        "# OK3D Stock App - Streamlit Cloud secrets",
        "# Generated by build_secrets_b64.py. Treat as a live credential.",
        "#",
        "# The service account is base64-encoded and folded across several lines.",
        "# Each line ends with a backslash, which TOML uses to join them back into",
        "# one string -- so a paste that wraps lines cannot corrupt it.",
        "",
    ]
    if spreadsheet_id:
        lines.append(f'spreadsheet_id = "{spreadsheet_id}"')
        lines.append("")

    # Triple-quoted, one trailing backslash per line: the fold.
    lines.append('gcp_service_account_b64 = """')
    for piece in body:
        lines.append(piece + "\\")
    lines.append('"""')
    return "\n".join(lines) + "\n"


def verify(block: str, expected_email: str) -> None:
    """Parse the block back and confirm the key survives intact."""
    try:
        import tomllib
    except ImportError:  # Python < 3.11
        import tomli as tomllib  # type: ignore

    data = tomllib.loads(block)
    encoded = data["gcp_service_account_b64"]
    if not isinstance(encoded, str):
        raise SystemExit("folded value did not parse to a string")

    # Whitespace tolerance mirrors what sheets_engine does at runtime.
    cleaned = "".join(encoded.split())
    account = json.loads(base64.b64decode(cleaned).decode("utf-8"))

    print("  toml parses                 : True")
    print(f"  has spreadsheet_id          : {'spreadsheet_id' in data}")
    print(f"  folded value length         : {len(encoded)} chars")
    print(f"  folded value line count     : {encoded.count(chr(10)) + 1}")
    print(f"  whitespace after cleaning   : {len(cleaned) != len(encoded)}")
    print(f"  decoded type                : {account.get('type')}")
    print(f"  decoded client_email        : {account.get('client_email')}")
    print(f"  email matches credentials   : {account.get('client_email') == expected_email}")
    private_key = account.get("private_key", "")
    print(f"  private_key lines preserved : {private_key.count(chr(10))}")
    print(f"  private_key has BEGIN/END   : "
          f"{'BEGIN PRIVATE KEY' in private_key and 'END PRIVATE KEY' in private_key}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    here = pathlib.Path(__file__).resolve().parent
    parser.add_argument("--credentials", type=pathlib.Path, default=here / "credentials.json")
    parser.add_argument("--spreadsheet-id", default=DEFAULT_SPREADSHEET_ID)
    parser.add_argument("--out", type=pathlib.Path, default=here / ".streamlit" / "secrets.toml")
    args = parser.parse_args(argv)

    if not args.credentials.exists():
        print(f"credentials.json not found at {args.credentials}")
        return 2

    raw = args.credentials.read_bytes()
    try:
        account = json.loads(raw.decode("utf-8"))
    except Exception as exc:  # noqa: BLE001
        print(f"credentials.json is not valid JSON: {exc}")
        return 2

    for field in ("type", "private_key", "client_email", "token_uri"):
        if field not in account:
            print(f"credentials.json is missing '{field}' - not a service-account key?")
            return 2
    if "BEGIN PRIVATE KEY" not in str(account["private_key"]):
        print("private_key does not look like a PEM key - refusing")
        return 2

    encoded = base64.b64encode(raw).decode("ascii")
    print(f"source            : {args.credentials}")
    print(f"client_email      : {account['client_email']}")
    print(f"base64 length     : {len(encoded)} chars")

    block = build_block(args.spreadsheet_id, encoded)
    print(f"block lines       : {block.count(chr(10))}")
    print()
    print("verifying...")
    verify(block, str(account["client_email"]))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(block, encoding="utf-8", newline="\n")
    print()
    print(f"written to        : {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
